### PR TITLE
Fix prefix handling in NgModelFormMixin

### PR DESCRIPTION
**Pull request by DavidCain**
If you have multiple forms in one page, and use Django's `prefix` attribute to distinguish them, Djangular will error out initializing the form:

    'NoneType' object has no attribute 'items'

The prefix-handling code within `NgModelFormMixin` was assuming that form data would be nested in a subdictionary by a prefix, like so:

```python
{'name': "Fred",
 'contact_info': {'name': 'Steve',
                  'phone': '555-1234'}
}
```

Instead, prefixed form data looks like this:
```python
{'name': "Fred",
 'contact_info.name': 'Steve',
 'contact_info.phone': '555-1234'
}
```

(Fields would normally be [`'contact_info-name'`][add_prefix] under Django 1.6-1.8, but Djangular overrides this to use a dot separator for Angular).

----------

I've tested this on Django 1.7 and 1.8. `_post_clean()` still works as expected.

[add_prefix]: https://github.com/django/django/blob/1.8.7/django/forms/forms.py#L186

### CODE REVIEW

File: djangular/forms/angular_model.py [hunk 1]
```diff
@@ -33,7 +33,7 @@ def __init__(self, data=None, *args, **kwargs):
             self.ng_directives['ng-model'] = '%(model)s'
         self.prefix = kwargs.get('prefix')
         if self.prefix and data:
-            data = dict((self.add_prefix(name), value) for name, value in data.get(self.prefix).items())
+            data = {name: value for name, value in data.items() if name.startswith(self.prefix + '.')}
```
Comment (jrief) [inline djangular/forms/angular_model.py]: AFAIK, this syntax for comprehensions does not work for Py2.
Does this work on python-2.7?

Comment (DavidCain) [inline djangular/forms/angular_model.py]: Dictionary comprehensions were introduced in Python 2.7. If you wish to support previous versions of Python, then `dict()` is definitely a better choice. (However, I'm taking it from setup.py that you're only supporting 2.7+, yes?)

Comment (jrief) [inline djangular/forms/angular_model.py]: You're right. I dropped support for Py26. Still unsure sometimes.

**Comment by jrief** [comment]
please also check the failing unit tests.

**Comment by DavidCain** [comment]
Will do - (probably won't have time tonight, but I'll check back).

**Comment by adrienbrunet** [comment]
We should close this PR and focus on #204 .
@DavidCain if you want to finish this work, feel free to reopen this PR, we will happily merge it if tests are passing. PR #204 seems to solve the same problem though. You can have a look if you have the time.

**Comment by DavidCain** [comment]
PR #204 looks great. Sorry I never got around to fixing up the tests on this one. Definitely agreed that it should close out!

**Comment by adrienbrunet** [comment]
:+1:
